// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIYLqA_hB55yKO8dJz2Tjzqcs1slNF8xk',
    appId: '1:736137128331:web:153701031e34e744e0678e',
    messagingSenderId: '736137128331',
    projectId: 'property-auth-137df',
    authDomain: 'property-auth-137df.firebaseapp.com',
    storageBucket: 'property-auth-137df.firebasestorage.app',
    measurementId: 'G-5CXDYXJFKY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDET-P9cjykBrfLI5nKx_m7bRnuq_za9qU',
    appId: '1:736137128331:android:ef20d6212cd3694ae0678e',
    messagingSenderId: '736137128331',
    projectId: 'property-auth-137df',
    storageBucket: 'property-auth-137df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl8B7bZyjpGqQEB0FDiAWqO4CPVCZKp74',
    appId: '1:736137128331:ios:5efdb32d0719cd85e0678e',
    messagingSenderId: '736137128331',
    projectId: 'property-auth-137df',
    storageBucket: 'property-auth-137df.firebasestorage.app',
    iosBundleId: 'com.example.afk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl8B7bZyjpGqQEB0FDiAWqO4CPVCZKp74',
    appId: '1:736137128331:ios:5efdb32d0719cd85e0678e',
    messagingSenderId: '736137128331',
    projectId: 'property-auth-137df',
    storageBucket: 'property-auth-137df.firebasestorage.app',
    iosBundleId: 'com.example.afk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIYLqA_hB55yKO8dJz2Tjzqcs1slNF8xk',
    appId: '1:736137128331:web:d22d90cb9e701377e0678e',
    messagingSenderId: '736137128331',
    projectId: 'property-auth-137df',
    authDomain: 'property-auth-137df.firebaseapp.com',
    storageBucket: 'property-auth-137df.firebasestorage.app',
    measurementId: 'G-LJ1LM37LH0',
  );
}
